#!/bin/bash
allScriptsFileName=".nestedScripts"
allScriptsFile="$(dirname "${BASH_SOURCE[0]}")/${allScriptsFileName}"

function dyno(){
    version=1.4
    declare -a commands
    
    commands=(
        "open::Opens current folder"
        "location::Shows the location of DYNO"
        "script::Open the 'dyno' Script file"
        "source::Source the Current file in Shell"
        "commands::List All commands created by DYNO"
        "location::Navigate to the source location of Dyno"
        "add::Add another source script"
        "repo::Opens the Github.com link of the current folder's git repo"
        "new::Add a New Script to folder"
        "help::List all the commands the available"
        "reset::Reset the script to the factory defaults"
    )
    
    #The following code helps in auto completion
    allCommands=""
    for index in "${commands[@]}" ; do
        key="${index%%::*}"
        allCommands+="${key} "
    done
    
    complete -W "${allCommands}" dyno

    subString(){
       
        local myresult="${1#*$2}" # removing prefix  
        myresult="${myresult%$3*}" # removing suffix
        echo "$myresult"
      
    }
    
    case $1 in
        "add")
            read -e -p "Enter the path of the new script to source: " FILE
            fullPath=$(realpath -m $FILE | sed 's/\~\///g')
            if test -f "$fullPath"; then
                if  [[ "$fullPath" -ef "$BASH_SOURCE" ]]; then
                    echo "You cannot add Me Again"
                else
                    echo "source \"$fullPath\""  >> "$BASH_SOURCE"
                    source "$BASH_SOURCE"
                fi
            else
                echo "$(realpath -m $fullPath) File does not exist."
            fi
        ;;
        "new")
            read -e -p "Enter the Directory of your Project: " FILE
            fullPath=$(realpath -m $FILE | sed 's/\~\///g')
            echo $fullPath
            if test -d "$fullPath"; then
                
                read -e -p "Enter the NAME (single word) of the project: " name
                
                echo "Downloading script template"
                cd "$fullPath"
                wget https://raw.githubusercontent.com/ashindiano/dyno/master/template
                if test -f "template"; then
                    
                    sed -i '' "s|_path_|\"$fullPath\"|g" "template"
                    sed -i '' "s/template/$name/g" "template"
                    mv "template"  ".dynoScript"
                    echo "# Ignore dyno tool s`up`port file" >> .gitignore
                    echo ".dynoScript" >> .gitignore
                    
                    echo "Adding $fullPath/.dynoScript to Bash sources list "
                    echo "source \"$fullPath/.dynoScript\""  >> ${allScriptsFile}
                    source "$BASH_SOURCE"
                    echo "Success: Project $name created "
                    echo "You can start using ' $name ' command"
                else
                    echo "File Download Error " >&2
                fi
                
            else
                echo "Directory does not exist."
            fi
            
        ;;
        "location")
            cd "$( dirname "${BASH_SOURCE[0]}" )"
        ;;
        "script")
            echo "Opening ${allScriptsFile}"
            code ${allScriptsFile}
        ;;
        "source")
            echo "Sourcing ${allScriptsFile}"
            source ${allScriptsFile}
        ;;
        "reset")
            echo "Are you sure you wanna reset Dyno? Yes/No"
            read answer
            if [["$answer" == "Yes"]]; then
                sed '/source/,$d'
            fi
        ;;

        "commands")        
            x=$(locate .dynoScript)
            IFS=$'\n' y=($x)
            for file in "${y[@]}" ; do 
              functionname=$(cat ${file})
              functionname=${functionname%()*}   
              echo "${functionname#*function }"
            done
        ;;

        "refresh")
            echo "Searching for all local dyno Projects created"
            case $(uname | tr '[:upper:]' '[:lower:]') in
                linux*)
                    sudo updatedb
                    ;;
                darwin*)
                    sudo /usr/libexec/locate.updatedb
                    ;;
                *)

                    ;;
            esac
            # sudo /usr/libexec/locate.updatedb
            echo "Search Complete refreshing Projects"
            x=$(locate .dynoScript)
            IFS=$'\n' y=($x)
            i=$(cat  ${allScriptsFile})
            IFS=$'\n' j=($i)
            for file in "${y[@]}" ; do 
                    local isFileExist=false
                    for sourcedFile in "${j[@]}" ; do
                        if [[ "$sourcedFile" == *"source "* ]]; then
                            
                            if [[ "$file" ==  *"$(subString "$sourcedFile" "source ")"* ]]; then
                                isFileExist=true
                                break
                            fi
                        fi
                   done
                   if [ $isFileExist = false ]; then
                        echo "source $file"  >> "${allScriptsFile}"
                   fi
            done
            echo "Refresh Complete"
        ;;

        "update")
            echo "Downloading new dyno version" 
                dynoPath=~/.dyno/dyno
                tmpPath=~/.dyno/.tmp
                wget -O ${tmpPath} https://raw.githubusercontent.com/ashindiano/dyno/master/dyno
                if test -f ${tmpPath}; then
                    mv -f ${tmpPath} ${dynoPath}
                    echo "Update Complete !!!" 
                    source "${BASH_SOURCE[0]}"
                else
                    echo "Download Failed !!!" 
                fi
        ;;

        "repo")
            echo "Opening current Git Repository in github.com" 

            remote=$(git config --get remote.origin.url)
            if [[ $remote != *".git"* ]]; then
                echo " No Git Found"
            else
                remote=${remote#*git@github.com:}   # remove prefix ending in "git@github.com:"
                remote=${remote%.git*}   # remove suffix starting with ".git"
                open "https://github.com/$remote"
            fi
        ;;
        
        "--version"|"-v")
            echo ${version}
        ;;

        "help"|"h"|"--help"|"-h")
            for index in "${commands[@]}" ; do
                key="${index%%::*}"
                value="${index##*::}"
                echo ${key} - ${value}
            done
            echo ""
            echo "Project commands by DYNO"
            echo "========================"
            x=$(locate .dynoScript)
            IFS=$'\n' y=($x)
            for file in "${y[@]}" ; do 
              functionname=$(cat ${file})
              functionname=${functionname%()*}   
              echo "${functionname#*function }"
            done
        ;;
        
    esac
}

dyno version #Run atleast once to list all autocomplete values


alias bye="systemctl poweroff -i"
alias reboo="systemctl reboot -i"
alias e=exit

source "${allScriptsFile}"
cd # Go back to the default folder
