#!/bin/bash
#version 1.0

function template(){
    declare -a commands
    commands=(
        "open::Opens current folder"
        "script::Open the 'template' Script file"
        "code::Open the folder in VS Code editor"
        "source::Source the Current file in Shell"
        "help::List all the commands the available"
    )
    
    #The following code helps in auto completion
    allCommands=""
    for index in "${commands[@]}" ; do
        key="${index%%::*}"
        allCommands+="${key} "
    done
    
    complete -W "${allCommands}" template
    #########
    
    cd _path_
    
    case $1 in
        
        "open")
            echo "Opening Current Folder"
            nautilus .
        ;;
        "script")
            echo "Opening $BASH_SOURCE"
            code "$BASH_SOURCE"
        ;;
        
        "code")
            code .
         ;;
         
        "source")
            echo "Sourcing $BASH_SOURCE"
            source "$BASH_SOURCE"
        ;;
        
        "repo")
            echo "Opening Github.com Repo"
            remote=$(git config --get remote.origin.url)
            remote=${remote#*git@github.com:}   # remove prefix ending in "git@github.com:"
            remote=${remote%.git*}   # remove suffix starting with ".git"
            open "https://github.com/$remote"
        ;;
        
        "help"|"h"|"--help"|"-h")
            for index in "${commands[@]}" ; do
                key="${index%%::*}"
                value="${index##*::}"
            done
        ;;
        
    esac
}

template
