name: Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate the changelog
      - name: Generate Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          version-file: './version.json'

      # Create a new release
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }} # Use secrets.WORKFLOW_PAT if needed; otherwise, replace with secrets.GITHUB_TOKEN
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
