# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT}}
          branch: main
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Update Version File
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo "updated versio ${RELEASE_VERSION}"
          echo $RELEASE_VERSION > version.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "version updated"
          git push origin HEAD:main
